update HANU description and add project intro
openinfradev/community pull request #13
Opened 2020-12-16 10:18 UTC by haksungjang

2020-12-22 02:19 UTC, bluejayKR reviewed
몇 군데 사소한 오탈자와 제 의견을 추가하였습니다.

2020-12-22 02:19 UTC, bluejayKR commented on governance/README.md
> +- HANU는 [OpenStack](https://www.openstack.org/)과 [Kubernetes](https://kubernetes.io/)를 쉽게 활용할 수 있는 환경을 구축하여 국내 Community를 확장하고 다시 Upstream에 기여하여 오픈소스 생태계에 기여합니다.
아래 정도는 어떨까요? 


HANU는 OpenStack를 중심으로 한 [Open Infrastructure](https://openinfra.dev/projects/) 산하 프로젝트들과 Kubernetes를 중심으로 한 [Cloud Native Computing](https://www.cncf.io/) 산하의 프로젝트들을 쉽게 활용할 수 있는 환경을 만들고, 필요한 기술을 오픈소스SW로 개발하여 공유할 수 있는 국내 Community를 만들어 확장합니다. 또한, 글로벌 Upstream 프로젝트에 기여할 수 공동체를 만들어 국내의 오픈소스 생태계 활성화에 기여합니다.

2020-12-22 02:19 UTC, bluejayKR commented on README.md
> +
참고로, '21년에는 HANUCTL로 명칭을 바꿀 예정입니다.  > 이 문구가 말미에 추가되면 좋겠습니다

2020-12-22 02:19 UTC, bluejayKR commented on README.md
>  HANU Community 운영과 관련한 문의/요청이 있을 경우 [Issue](https://github.com/openinfradev/community-draft/issues/new)를 생성해서 의견 남겨 주세요.
commnity-draft에서 community로 repo이름이 변경되었으니, 이를 반영해서 수정 필요합니다 
[issue](https://github.com/openinfradev/community/issues/new)

2020-12-22 02:19 UTC, bluejayKR commented on governance/README.md
>  * SIG (Special Interest Group)
아래 내용이 추가되어야 할까요? 

각 프로젝트별로 PTL (Project Technical Leader)를 두며, 해당 프로젝트내에서 발생하는 기술적인 이슈에 대한 논의를 이끌어 갈 수 있도록 합니다.

2020-12-22 02:19 UTC, bluejayKR commented on governance/README.md
>  * Reviewer
Reviewer라고 하는게 좋을지 모르겠네요. 아래 정도는 어떨까요? 물론, 추가적으로 Contributor는 어떻게 되는지, Committer는 어떻게 되는지를 문서화 해야 하지만, 일단은 여기서는 아래 정도만 정의해두고, 관련된 추가 정보는 업데이트 예정이라고 하면 

- Member : 프로젝트에 참여하는 전원 
- Contributor : 코드, 문서등 github repository에 직접적인 기여를 한 개발자 
- Committer: 코드에 대한 리뷰와 Merge권한을 가진 개발자

2020-12-22 02:19 UTC, bluejayKR commented on governance/README.md
> +HANU의 Governance에 대해 문의나 의견이 있을 경우 [Issue](https://github.com/openinfradev/community-draft/issues/new)를 생성해주세요.
commnity-draft에서 community로 repo이름이 변경되었으니, 이를 반영해서 수정 필요합니다 
[issue](https://github.com/openinfradev/community/issues/new)

2020-12-22 02:19 UTC, bluejayKR commented on governance/group.md
> +기술 위원회의 멤버는 매년 선거를 통해 결정합니다. 선거 방법은 다음 페이지를 참고하세요. : [HANU 선거 절차](election.md)
일단 PTL 개념이 들어오면, 아래와 같이 되어야 하지 않을까요? 물론, 몇 명을 선출해야 하는지에 대해서 추가로 정의가 필요하지만 

**기술 위원회는 산하 프로젝트의 PTL들과 매년 선거를 통해서 선출된 멤버로 이루어 집니다.**

2020-12-22 06:51 UTC, haksungjang commented on governance/README.md
>  * SIG (Special Interest Group)
Group에 Project를 추가하고, 말씀하신 PTL의 역할을 추가하는 방향으로 보완해보겠습니다.

2020-12-22 07:51 UTC, haksungjang commented on README.md
> +HANU 프로젝트는 Open Infrastructure와 관련된 오픈소스 기술들을 모아 제공하고, 이를 기반으로 커뮤니티 구성 및 확산시키기 위한 공간입니다.
의견 주신 사항 반영하여 commit 추가하였습니다.

2020-12-22 07:52 UTC, haksungjang commented on governance/README.md
> +- HANU는 [OpenStack](https://www.openstack.org/)과 [Kubernetes](https://kubernetes.io/)를 쉽게 활용할 수 있는 환경을 구축하여 국내 Community를 확장하고 다시 Upstream에 기여하여 오픈소스 생태계에 기여합니다.
네, 의견 주신 사항 반영하여 commit 추가하였습니다.

2020-12-22 07:52 UTC, haksungjang commented on README.md
>  HANU Community 운영과 관련한 문의/요청이 있을 경우 [Issue](https://github.com/openinfradev/community-draft/issues/new)를 생성해서 의견 남겨 주세요.
네, 일괄 반영하였습니다. 의견 감사합니다.

2020-12-22 07:52 UTC, haksungjang commented on governance/README.md
>  * SIG (Special Interest Group)
이 사항은 Membership 보완 시 추가 반영하겠습니다.

2020-12-22 07:53 UTC, haksungjang commented on governance/README.md
>  * Reviewer
의견 감사합니다. 일단, 반영하였으며, 추가로 Membership 내용 보완 시 추가 반영 하겠습니다.

2020-12-22 07:53 UTC, haksungjang commented on governance/group.md
> +기술 위원회의 멤버는 매년 선거를 통해 결정합니다. 선거 방법은 다음 페이지를 참고하세요. : [HANU 선거 절차](election.md)
네, 의견 주신 사항 반영하였습니다. 감사합니다.

2020-12-22 07:56 UTC, haksungjang commented on README.md
>  HANU Community 내 Project는 각각의 READE에서 사용/설치/운영 방법을 자세히 소개합니다.
확인 감사합니다. 수정하였습니다. : a2b6d91fd6a4227b2c63ae933d504b4176bc4621

2020-12-22 07:57 UTC, haksungjang commented on README.md
> +
네, 추가하였습니다. : a2b6d91fd6a4227b2c63ae933d504b4176bc4621

2020-12-22 08:01 UTC, haksungjang commented on governance/README.md
> +HANU의 Governance에 대해 문의나 의견이 있을 경우 [Issue](https://github.com/openinfradev/community-draft/issues/new)를 생성해주세요.
네, 일괄 반영하였습니다.: a2b6d91fd6a4227b2c63ae933d504b4176bc4621
감사합니다.

2020-12-23 04:48 UTC, bluejayKR requested changes
몇 가지 수정사항을 제안드렸습니다. 이 부분만 반영되면 우선 Merge해도 좋을 듯 합니다. 
보완이나 추가가 필요한 내용들은, 차례 차례 별도의 PR을 통해서 추가해나가구요. 

수고 많으셨습니다.

2020-12-23 04:48 UTC, bluejayKR commented on README.md
> +## HANU (HAm Gye NUrim; 함께 누림)
국어의 영문표기법을 찾아보았습니다.

**HA**m kke **NU** rim 으로 표기하면 좋을 것 같습니다.

2020-12-23 04:48 UTC, bluejayKR commented on README.md
> +
아래와 같이 수정해 보았습니다. 

HANU에는 여러 개의 오픈소스SW 프로젝트들이 있습니다. HANU의 프로젝트들은 각각 고유의 기능/구조적 특징을 가지면서, 필요 시 서로 연계할 수 있도록 되어 있습니다. 

HANU의 프로젝트는 두 개로 나뉘어 집니다. 첫번째로 Incubation Project로 시작이 되며, 그 이후 충분한 기능적 완성도와 안성정을 갖추게 되면 Stable Project로 전환 될 수 있습니다. 

Incubation Project는 누구든지 생성을 제안할 수 있으며, Technical Committee에서 결정합니다.

2020-12-23 04:48 UTC, bluejayKR commented on README.md
> +Ansible 기반의 Baremental, Jubernetes, Add-on tools에 대한 설치 자동화 소프트웨어입니다.
오탈자입니다. Jubernetes --> Kubernetes 

문구는 다음과 같이 수정하는게 좋을 듯 합니다. 

Ansible기반의 Baremetal, Docker, Kubernetes 설치 자동화 기능을 제공하며, 설치된 Kubernetes 상에서 Airship Armada 혹은  decapod를 활용하여 컨테이너화된 OpenStack 이나 LMA (Logging, Monitoring, Alerting), 혹은 추가 Add-on tools 들을 설치할 수 있는 ansible playbook들을 제공합니다.

2020-12-23 10:02 UTC, haksungjang commented on README.md
> +## HANU (HAm Gye NUrim; 함께 누림)
네, 수정하였습니다. : ef7aaad80b89cbe9b1fb1e454f9a646dbbd967ec

2020-12-23 10:03 UTC, haksungjang commented on README.md
> +
네, 반영하였습니다. : ef7aaad80b89cbe9b1fb1e454f9a646dbbd967ec

2020-12-23 10:03 UTC, haksungjang commented on README.md
> +Ansible 기반의 Baremental, Jubernetes, Add-on tools에 대한 설치 자동화 소프트웨어입니다.
네, 반영하였습니다! : ef7aaad80b89cbe9b1fb1e454f9a646dbbd967ec

2020-12-24 03:21 UTC, bluejayKR approved these changes

2020-12-24 04:19 UTC, funfunyoo commented
다들 너무 잘 정리해주셔서 의견을 달지 않았었는데 리뷰가 있었군요. ;;;

2020-12-24 04:43 UTC, merged